apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ollama-webui
  name: ollama-webui-storage
  namespace: ollama-llm
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 12Gi
