apiVersion: v1
kind: Service
metadata:
  name: ollama-api-service
  namespace: ollama-llm
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
      name: internal-api
    - protocol: TCP
      port: 80
      targetPort: 11434
      name: external
