kind: ServiceAccount
apiVersion: v1
metadata:
  name: ollama-llm-sa
  namespace: ollama-llm
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:privileged'
subjects:
  - kind: ServiceAccount
    name: ollama-llm-sa
    namespace: ollama-llm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
